# Generated by Django 3.2.5 on 2022-08-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_b64',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
