# Generated by Django 3.2.5 on 2022-08-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='info',
            field=models.CharField(default='Info config', max_length=250, verbose_name='Info config'),
        ),
    ]
